### PR TITLE
Add section with demo link

### LINKED ISSUE #46: Demo?
Hi @wooorm 👋

What are your thoughts on adding a link to an interactive demo to the readme?

I've made so many demo repls on Replit for refractor when I needed to debug something - would be cool to be able to just click on the existing demo and modify some things!

### PR DESCRIPTION
**Pull request by karlhorky**
I transformed the hast to HTML with `hast-util-to-html`, what do you think?

Closes #46

### CODE REVIEW

**Comment by wooorm** [comment]
Maybe a little note before the first `.register` call to mention that most common languages (https://github.com/wooorm/refractor#syntaxes) are pre-registered?

Otherwise :+1:

**Comment by karlhorky** [comment]
Great idea, added! Also updated the URL to denote that it's the official demo.

And feel free to fork to have ownership.

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Sweet, thanks!

**Comment by karlhorky** [comment]
Glad to help! Thanks for the merge!

**Pull request merged**
